README.md, lib/DirectoryWatcher.js, lib/watchpack.js
Usage from webpack:
```js
watchOptions: {
ignored: /node_modules/
}
```
This option will prevent watchpack from watching certain files/directories, which can improve performance when polling. A common scenario is to ignore the `node_modules` directory since you don't normally edit those files during development.
=> Add `ignored` option

lib/DirectoryWatcher.js
It seems that the `createNestedWatched` function refers to `this.options` when creating a nested watcher, but this is never defined when creating the instance, so nested watchers do not get the correct options passed into them.
This manifested itself for me in polling for file changes (over a VirtualBox mount with either vboxsf or nfs) not working for deeply nested directories.
I'm not familiar with the Watchpack code so perhaps this isn't the correct/best fix, but it fixed my problem :) Open to any comments to improve it!
=> Store the options passed when contructing the DirectoryWatcher as an instance variable

lib/DirectoryWatcher.js
If vim is set up to use a swap file, then when a save is changed, it
deletes the original file and renames the swap file into place.  This
can sometimes cause chokidar to send two events: "remove" and "add".
Because the DirectoryWatcher doesn't clear out removed files, the
subsequent add event is ignored and the change is not seen.
=> Handle files that are deleted and recreated

lib/DirectoryWatcher.js, test/DirectoryWatcher.test.js
It looks we have to check if `mtime` exists.
=> Fix remove event is not emitted

lib/DirectoryWatcher.js
I believe this will fix webpack/webpack#762. I discovered that watch mode was firing an immediate rebuild because it thought files had changed that _were_ changed immediately prior to watch running, but not during the watch build. I think after this change there's still the possibility that sometimes a second rebuild is fired immediately, but the time window for it should be much shorter.
Let me know if I'm missing something.
Cheers!
=> Fixes webpack/webpack#762

lib/DirectoryWatcher.js, package.json, test/Watchpack.js
Updated Chokidar
Set new chokidar "disableGlobbing" feature to "true"
Added test to prevent regression
Fixes #42 
Fixes webpack/webpack#4250
Fixes angular/angular-cli#6823
Fixes aspnet/JavaScriptServices#767
=> Fixed watch for directories containing special glob characters

lib/DirectoryWatcher.js
Chokidar differentiates the polling interval for source files and binary files.  Passing only the `interval` option will make chokidar to poll binary files (ex: images) every 300ms (the default value) instead of the value specified by the webpack `watchOptions.poll` value.
You can verify this by using something like `strace -f -p $NODE_PID -e stat` to check the `stat` frequency for all watched files.
=> Fix polling interval for binary files

lib/DirectoryWatcher.js
fixes bug accidentally merged in #70
=> fix incorrect context

lib/DirectoryWatcher.js, test/DirectoryWatcher.test.js
This fixes issue:
https://github.com/webpack/webpack/issues/8101
There doesn't seem to be any channel for watchpack to report errors up to webpack which is probably a better long term solution but this at least gives users relevant error messages. 
The test isn't super great  but since watchpack ignores access errors I can't come up with a way to trigger a real error without sudo but I have tested it manually by using yarn link and setting my inotify.max_user_watches to a low value and it reports the errors correctly.
=> Output errors from chokidar to stderr

test/DirectoryWatcher.test.js
Currently the "should detect a file removal" test doesn't run the assertion at all due to shouldjs change ( https://github.com/shouldjs/should.js/wiki/Breaking-changes#changes-for-7x )
Fixing this causes the test to fail (1st commit)
Looks like the event signature for removal changed at some point as well so this also changes to match that so the test passes. (2nd commit)
=> Fix removal test

.travis.yml, appveyor.yml
=> [dnm] chore: remove Node.js 4, add Node.js 10

README.md, lib/DirectoryWatcher.js, lib/LinkResolver.js, lib/watchpack.js, test/Watchpack.js, test/helpers/TestHelper.js
=> add `followSymlinks` options and handle symlinks correctly

README.md, lib/DirectoryWatcher.js, lib/watchpack.js, test/Watchpack.js
* add `missing` items to watch API
* report file/directory removal when missing in initial scan
* report explanation on event API
* add `remove` event
* aggregate event reports either removal or change
* merge watchers into single array
=> report initial removal

lib/watchpack.js
Handles : [#10071](https://github.com/webpack/webpack/issues/10071)
Aligned with 
https://github.com/webpack/webpack/pull/10118
=> Fix:10071 - Accept watchOptions.aggregateTimeout be 0

lib/DirectoryWatcher.js, test/Casing.js, test/helpers/TestHelper.js
As noticed in https://github.com/zeit/next.js/pull/10351 when a filename's casing is changed both variants of the filename are reported from `getTimeInfoEntries`. This makes users unable rely on `getTimeInfoEntries` as a safe source of truth on case insensitive file systems.
This PR attempts to correct this by when an event is triggered for a file that is already in the watcher's files it re-checks that the file is still present with exact casing by doing a `readdir` on the directory the file resides in.
The added test cases were tested and previously failing on:
- MacOS 10.14.6 (node: v12.14.1)
- Windows 10 Pro 1809 (node: v10.15.3)
I also tested against the added test case in https://github.com/zeit/next.js/pull/10351 to double check this has the expected behavior.
=> Fix case renames not marking previous casing as missing in time entries

lib/DirectoryWatcher.js, test/Watchpack.js
when watching without start time
fixes #144
=> fix incorrect change events for nested directory 

package.json
https://npmjs.com/advisories/1179
Chokidar `2.0.5` does not exist yet but there's a PR to cascade this fix down: https://github.com/paulmillr/chokidar/pull/993
=> Update Chokidar to the new minor version that fixes the prototype pollution vulnerability through minmimist

lib/DirectoryWatcher.js
`insenstive` -> `insensitive`
Follow up of #143
=> Minor typographical fix

.travis.yml, appveyor.yml, azure-pipelines.yml, lib/DirectoryWatcher.js, lib/getWatcherManager.js, lib/reducePlan.js, lib/watchEventSource.js, lib/watchpack.js, test/ManyWatchers.js, test/Watchpack.js, test/helpers/TestHelper.js
This adds an additional layer for os watchers, which take care of merging duplicate watchers and merging watchers into recursive watchers once the watcher limit has been reached.
* default watcher limit is 2000 on OSX and 10000 on other platforms
* It's changeable via `WATCHPACK_WATCHER_LIMIT` environment variable
* only OSX and windows are enabled for recursive watching
* watchers will be merged into recursive watchers
* Watcher creation is batched in the facade to allow to make the decision about merging with all info
* once the limit would be reached we make a new watch plan using recursive watchers
* even existing watchers are reconsidered and possible migrated to the new watch plan
* watchers are merged based on how to reach the limit most effectively, while merging the fewest amount …
=> Merge watchers

lib/DirectoryWatcher.js, lib/watchpack.js, test/Watchpack.js
@Knagis @evilebottnawi should fix the unnecessary invalidation with contextDependencies (hopefully)
=> fix incorrectly reported changes when attaching to an already watched directory

lib/DirectoryWatcher.js, test/Watchpack.js
fixes https://github.com/webpack/webpack/issues/12140
=> use birthtime for folders instead of modified time

lib/LinkResolver.js, test/LinkResolver.js
Solves for use case where Webpack is running under Bazel
with iBazel. Heavily relies on symlinks set up in a certain way.
Essentially we don't want Webpack to follow symlinks, but we do want the watcher
to follow symlinks. In that setup, it causes an `ENOENT` which does not fall through in
watchpack under `darwin` as the platform (or linux for that matter). This fixes that case.
See https://github.com/bazelbuild/rules_nodejs/pull/2431
CC @sokra @gregmagolan @mrmeku
=> fix: adds ENOENT for non windows platforms in LinkResolver.

test/helpers/TestHelper.js
Fix the instability in polling tests with pausing the watcher due to multiple ticks in the same polling interval.
This will cause the test passes of https://github.com/webpack/watchpack/pull/205 and https://github.com/webpack/watchpack/pull/197 to complete successfully.
cc @alexander-akait
=> test: fix instability in polling tests

README.md, lib/DirectoryWatcher.js, lib/watchpack.js, test/Watchpack.js
The globs are turned into regex's anyway, so seems like a pretty simple change. Have a webpack discussion thread on the topic as well where I suggest aligning `watchOptions.ignored` and `WatchIgnorePlugin`
=> Allow function in `watchOptions.ignored`

lib/DirectoryWatcher.js
Should resolve https://github.com/webpack/webpack/issues/15431
After noodling on the discussions there and looking at past similar work done (namely https://github.com/webpack/watchpack/commit/164007c891d796a4f5e3ff60fc461ca8c416542f), I think this is the best way to resolve that issue while still doing best-effort to respect file systems with lower mtime accuracy.
Right now, the `if` check I am changing has an arbitrary 1s, while everywhere else is properly using the FS_ACCURACY, which will get updated to higher resolution if possible.
I think this is the best we can do without adding an optional dep of `fsevents` (fwiw, for OSX, chokidar will either use fsevents, or fall back to polling)
```
mtime + FS_ACCURACY < now - 1000
=
mtime + FS_ACCURACY + 1000 < now
> replace 1000 with …
```
=> Respect FS_ACCURACY when determining if file is untouched

lib/DirectoryWatcher.js, test/DirectoryWatcher.js
fixes https://github.com/webpack/watchpack/pull/227
fixes https://github.com/webpack/watchpack/issues/224
=> fix: do not report directory as initial missing on the second watch

lib/watchEventSource.js, test/Assumption.js
After Node.js v22, fs.watch(dir) and deleting a dir will trigger the rename change event.
Here we just ignore it and keep the same behavior as before v22
https://github.com/libuv/libuv/pull/4376
=> fix: ignore listening for the directory itself to be deleted

lib/watchEventSource.js, test/ManyWatchers.js
Limit the number of concurrently open file watchers on macOS to 20 to make `FSWatcher.close` faster.
Related PRs:
- https://github.com/vercel/next.js/pull/51826
- https://github.com/vercel/next.js/pull/73741
- https://github.com/web-infra-dev/rspack/pull/5486 (We tried setting WATCHPACK_WATCHER_LIMIT by default in the Rspack CLI, but I found that this did not work because watchpack was loaded earlier than the WATCHPACK_WATCHER_LIMIT was set in the Rspack CLI)
Related issues:
- https://github.com/webpack/watchpack/issues/222
- https://github.com/nodejs/node/issues/29949
=> perf: limit the number of concurrently open file watchers on macOS
